// Portions of this project were developed using suggestions generated by ChatGPT (OpenAI)
// 18/12/2024: https://chatgpt.com/c/67633ddc-f354-800a-9e65-13a770daff34
// Modifications made by Raiko Moons

"use strict";
import context from "./scripts/context.js";
import * as Utils from "./scripts/utils.js";

let width = context.canvas.width;
let lineWidth = 4;
let circlesWidth = 8;
let frame = 0;
let mouseX = width / 2;
let mouseY = context.canvas.height / 2;

context.canvas.addEventListener("mousemove", (event) => {
	const rect = context.canvas.getBoundingClientRect();
	mouseX = event.clientX - rect.left;
	mouseY = event.clientY - rect.top;
});

animate();

function animate() {
	context.clearRect(0, 0, context.canvas.width, context.canvas.height);
	drawTshirtDesign();
	blackCircles();
	frame++;
	requestAnimationFrame(animate);
}

function getRandomHue() {
	return Utils.randomNumber(120, 360);
}

function drawTshirtDesign() {
	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 40);
	Utils.strokeCircle(mouseX, mouseY, 100, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 50);
	Utils.strokeCircle(mouseX, mouseY, 120, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 40);
	Utils.strokeCircle(mouseX, mouseY, 70, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 60);
	Utils.strokeCircle(mouseX + 100, mouseY - 200, 40, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 20);
	Utils.strokeCircle(mouseX - 100, mouseY - 170, 20, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 20);
	Utils.strokeCircle(mouseX + 100, mouseY + 205, 40, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 40);
	Utils.strokeCircle(mouseX - 100, mouseY + 150, 30, 100);

	context.lineWidth = lineWidth;
	context.strokeStyle = Utils.hsl(getRandomHue(), 180, 40);
	for (let i = 1; i < 4; i++) {
		Utils.strokeCircle(mouseX, mouseY + 280, 30 + i * 10);
	}
}

function blackCircles() {
	let groteVeranderen = Math.sin(frame * 0.04) * 20;

	context.lineWidth = circlesWidth;
	context.strokeStyle = "black";
	Utils.strokeCircle(mouseX, mouseY + 100, 75 + groteVeranderen, 100);

	context.lineWidth = circlesWidth;
	context.strokeStyle = "black";
	Utils.strokeCircle(mouseX, mouseY - 100, 40 + groteVeranderen, 100);

	context.lineWidth = circlesWidth;
	context.strokeStyle = "black";
	Utils.strokeCircle(mouseX + 150, mouseY + 250, 80 + groteVeranderen, 100);

	context.lineWidth = circlesWidth;
	context.strokeStyle = "black";
	Utils.strokeCircle(mouseX + 150, mouseY - 185, 30 + groteVeranderen, 100);
}
